const CHANGE_REQUEST_FORM = "CHANGE_REQUEST_FORM";
const SET_RESPONSE_JSON = "SET_RESPONSE_JSON";
const SET_REQUEST_JSON = "SET_REQUEST_JSON";

export { CHANGE_REQUEST_FORM, SET_RESPONSE_JSON, SET_REQUEST_JSON };
