const CHANGE_REQUEST_FORM = "CHANGE_REQUEST_FORM";
const SET_RESPONSE_JSON = "SET_RESPONSE_JSON";
const SET_REQUEST_JSON = "SET_REQUEST_JSON";
const TOGGLE_LOADING = "TOGGLE_LOADING";

export {
  CHANGE_REQUEST_FORM,
  SET_RESPONSE_JSON,
  SET_REQUEST_JSON,
  TOGGLE_LOADING,
};
